import { z } from 'zod';
import type { Story, Dependency, RefinedPlan, AdvisorReview, RemoveStoryPayload, PersistedStoryRuntime, PersistedTask, ProjectState, StoryAgents } from './ipc';

const ThinkingLevelSchema = z.enum(['off', 'low', 'medium', 'high']);
const AgentConfigSchema = z.object({
  model: z.string().optional(),
  thinking: ThinkingLevelSchema.optional(),
});
export const StoryAgentsSchema = z.object({
  plan: AgentConfigSchema.optional(),
  code: AgentConfigSchema.optional(),
  qa: AgentConfigSchema.optional(),
}) satisfies z.ZodType<StoryAgents>;

/**
 * `StoryCoreSchema` is the model-facing shape (no taskId — taskIds are stamped
 * by NightCoder after the refiner returns, not generated by the model).
 * `StorySchema` is the runtime shape everywhere else.
 */
export const StoryCoreSchema = z.object({
  title: z.string().min(3).max(120),
  description: z.string().min(10),
  acceptanceCriteria: z.array(z.string().min(3)).min(1).max(12),
  affectedFiles: z.array(z.string()).max(40),
  model: z.string().optional(),
  agents: StoryAgentsSchema.optional(),
});

export const StorySchema = StoryCoreSchema.extend({
  taskId: z.string().min(1).max(80),
  numericId: z.number().int().min(1).optional(),
}) satisfies z.ZodType<Story>;

export const DependencySchema = z.object({
  from: z.number().int().min(0),
  to: z.number().int().min(0),
  reason: z.string().min(3),
}) satisfies z.ZodType<Dependency>;

export const RefinedPlanCoreSchema = z.object({
  stories: z.array(StoryCoreSchema).min(1).max(10),
  dependencies: z.array(DependencySchema),
});

export const RefinedPlanSchema = z.object({
  stories: z.array(StorySchema).min(1).max(10),
  dependencies: z.array(DependencySchema),
}) satisfies z.ZodType<RefinedPlan>;

export const RemoveStoryPayloadSchema = z.object({
  storyIndex: z.number().int().min(0),
}) satisfies z.ZodType<RemoveStoryPayload>;

const PersistedStorySchema = z.object({
  taskId: z.string().optional(),
  title: z.string(),
  description: z.string(),
  acceptanceCriteria: z.array(z.string()).default([]),
  affectedFiles: z.array(z.string()).default([]),
  model: z.string().optional(),
  agents: StoryAgentsSchema.optional(),
});

const PersistedDependencySchema = z.object({
  from: z.number().int().min(0),
  to: z.number().int().min(0),
  reason: z.string().default(''),
});

export const PersistedPlanSchema = z.object({
  stories: z.array(PersistedStorySchema).default([]),
  dependencies: z.array(PersistedDependencySchema).default([]),
});

export const PersistedStoryRuntimeSchema = z.object({
  status: z.enum(['pending', 'blocked', 'running', 'pushing', 'review', 'done', 'failed', 'cancelled', 'interrupted']),
  branch: z.string().nullable(),
  prUrl: z.string().nullable(),
  startedAt: z.number().nullable(),
  endedAt: z.number().nullable(),
  limitResetsAt: z.number().nullable().optional(),
}) satisfies z.ZodType<PersistedStoryRuntime>;

export const PersistedRuntimeSchema = z.record(
  z.coerce.number(),
  PersistedStoryRuntimeSchema,
);

export const PersistedTaskSchema = z.object({
  taskId: z.string().min(1),
  status: z.enum(['pending', 'blocked', 'running', 'pushing', 'review', 'done', 'failed', 'cancelled', 'interrupted']),
  branch: z.string().nullable(),
  prUrl: z.string().nullable(),
  startedAt: z.number().nullable(),
  endedAt: z.number().nullable(),
  sessionId: z.string().optional(),
  limitResetsAt: z.number().nullable().optional(),
}) satisfies z.ZodType<PersistedTask>;

/**
 * Schema for persisted per-project state. Strict on taskId (that's the load-
 * bearing key for resume) but lenient on free-text fields so user-typed
 * stories that are still short don't get rejected on rehydrate.
 */
const ProjectPlanStorySchema = z.object({
  taskId: z.string().min(1).max(80),
  numericId: z.number().int().min(1).optional(),
  title: z.string(),
  description: z.string(),
  acceptanceCriteria: z.array(z.string()).default([]),
  affectedFiles: z.array(z.string()).default([]),
  model: z.string().optional(),
  agents: StoryAgentsSchema.optional(),
});

const ProjectPlanSchema = z.object({
  stories: z.array(ProjectPlanStorySchema).default([]),
  dependencies: z.array(PersistedDependencySchema).default([]),
});

export const ProjectStateSchema = z.object({
  version: z.literal(1),
  brief: z.string().default(''),
  plan: ProjectPlanSchema,
  tasks: z.record(z.string(), PersistedTaskSchema).default({}),
  nextTaskNum: z.number().int().min(1).default(1),
}) satisfies z.ZodType<ProjectState>;

export const AdvisorReviewSchema = z.object({
  overall: z.string().min(1),
  concerns: z.array(z.string().min(1)),
  perStoryNotes: z.array(
    z.object({
      storyIndex: z.number().int().min(0),
      note: z.string().min(1),
    })
  ),
  suggestedDependencies: z.array(DependencySchema),
}) satisfies z.ZodType<AdvisorReview>;
