import type { Story, StoryStatus } from '@zibby/shared-types/ipc';
import { runClaudeInWorktree } from '@zibby/claude-runner';
import { commitAllIfDirty, gitPush, ghCreatePr } from '@zibby/github';
import { createWorktree, type WorktreeHandle } from './worktree';
import { slugify, uniqueSlug } from './slug';

export type StoryExecutionEvent =
  | { kind: 'status'; status: StoryStatus }
  | { kind: 'log'; stream: 'stdout' | 'stderr' | 'info'; line: string }
  | { kind: 'pr'; url: string; branch: string };

export type StoryExecutionResult = {
  success: boolean;
  prUrl?: string;
  branch?: string;
  error?: string;
};

function buildPrompt(story: Story): string {
  const ac = story.acceptanceCriteria.map((c, i) => `${i + 1}. ${c}`).join('\n');
  const files = story.affectedFiles.length > 0 ? `\n\nExpected files to touch: ${story.affectedFiles.join(', ')}` : '';
  return `Implement the following user story end-to-end in this repository.

# ${story.title}

${story.description}

## Acceptance criteria

${ac}${files}

Guidelines:
- You are working inside a git worktree on a fresh feature branch. Make commits as you go so work is not lost.
- Run existing test/lint/typecheck commands if present and keep them green.
- Respect the repository's own CLAUDE.md / AGENTS.md and other AI convention files.
- When every acceptance criterion is met and tests pass, make a final commit and stop — the outer tool will push and open a PR.`;
}

function buildPrBody(story: Story): string {
  const ac = story.acceptanceCriteria.map((c) => `- [ ] ${c}`).join('\n');
  return `## Summary

${story.description}

## Acceptance criteria

${ac}

---

🤖 Auto-generated by Zibby 2.0.`;
}

export async function executeStory(args: {
  story: Story;
  storyIndex: number;
  repoPath: string;
  baseBranch: string;
  usedSlugs: Set<string>;
  onEvent: (event: StoryExecutionEvent) => void;
  signal: { cancelled: boolean };
}): Promise<StoryExecutionResult> {
  const { story, repoPath, baseBranch, usedSlugs, onEvent, signal } = args;
  const slugBase = slugify(`${args.storyIndex + 1}-${story.title}`);
  const slug = uniqueSlug(slugBase, usedSlugs);
  usedSlugs.add(slug);

  onEvent({ kind: 'status', status: 'running' });

  let worktree: WorktreeHandle | null = null;
  try {
    worktree = await createWorktree({
      repoPath,
      slug,
      baseBranch,
      onInfo: (msg) => onEvent({ kind: 'log', stream: 'info', line: msg }),
    });
    onEvent({ kind: 'log', stream: 'info', line: `worktree ${worktree.path} (branch ${worktree.branch})` });

    const handle = runClaudeInWorktree(
      { cwd: worktree.path, prompt: buildPrompt(story), addDirs: [] },
      {
        onEvent: (e) => {
          const tag = e.kind === 'tool' ? `tool: ${e.line}` : e.kind === 'text' ? e.line : e.kind === 'error' ? `error: ${e.line}` : e.line;
          onEvent({ kind: 'log', stream: 'stdout', line: tag });
        },
        onStderr: (line) => onEvent({ kind: 'log', stream: 'stderr', line }),
      }
    );

    const cancelWatcher = setInterval(() => {
      if (signal.cancelled) handle.cancel();
    }, 500);

    const result = await handle.result;
    clearInterval(cancelWatcher);

    if (signal.cancelled) {
      onEvent({ kind: 'status', status: 'cancelled' });
      return { success: false, error: 'cancelled' };
    }
    if (!result.success) {
      onEvent({ kind: 'status', status: 'failed' });
      return { success: false, error: result.error ?? `stop_reason=${result.stopReason ?? '?'}` };
    }

    onEvent({ kind: 'status', status: 'pushing' });
    const madeCommit = await commitAllIfDirty(worktree.path, `chore(zibby): flush uncommitted changes for ${story.title}`);
    if (madeCommit) onEvent({ kind: 'log', stream: 'info', line: 'flushed uncommitted changes into final commit' });
    await gitPush(worktree.path, worktree.branch);
    onEvent({ kind: 'log', stream: 'info', line: `pushed ${worktree.branch}` });
    const prUrl = await ghCreatePr({
      cwd: worktree.path,
      title: story.title,
      body: buildPrBody(story),
      baseBranch,
    });
    onEvent({ kind: 'pr', url: prUrl, branch: worktree.branch });
    onEvent({ kind: 'status', status: 'done' });
    return { success: true, prUrl, branch: worktree.branch };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    onEvent({ kind: 'log', stream: 'stderr', line: message });
    onEvent({ kind: 'status', status: 'failed' });
    return { success: false, error: message };
  } finally {
    if (worktree) {
      await worktree.cleanup().catch((e) => {
        onEvent({ kind: 'log', stream: 'stderr', line: `worktree cleanup failed: ${e instanceof Error ? e.message : String(e)}` });
      });
    }
  }
}
