import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import path from 'node:path';
import type { Story, StoryStatus } from '@nightcoder/shared-types/ipc';
import { runClaudeInWorktree } from '@nightcoder/claude-runner';
import { commitAllIfDirty, gitPush, ghCreatePr } from '@nightcoder/github';
import {
  appendJournalLine,
  ensureTaskDir,
  journalPath,
  writePlanMd,
} from '@nightcoder/project-state';
import { createWorktree, type WorktreeHandle } from './worktree';
import { slugify, uniqueSlug } from './slug';
import { tryClaimStory } from './active-stories';
import { installPostCommitHook } from './post-commit-hook';

const execFileP = promisify(execFile);
const POLL_INTERVAL_MS = 2000;
const PLAN_BLOCK_RE = /<plan>([\s\S]*?)<\/plan>/i;

export type StoryExecutionEvent =
  | { kind: 'status'; status: StoryStatus }
  | { kind: 'log'; stream: 'stdout' | 'stderr' | 'info'; line: string }
  | { kind: 'pr'; url: string; branch: string };

export type StoryExecutionResult = {
  success: boolean;
  prUrl?: string;
  branch?: string;
  error?: string;
  duplicate?: boolean;
};

function buildPrompt(story: Story): string {
  const ac = story.acceptanceCriteria.map((c, i) => `${i + 1}. ${c}`).join('\n');
  const files = story.affectedFiles.length > 0 ? `\n\nExpected files to touch: ${story.affectedFiles.join(', ')}` : '';
  return `Implement the following user story end-to-end in this repository.

# ${story.title}

${story.description}

## Acceptance criteria

${ac}${files}

Process guidelines:
- Before coding, output your implementation plan inside a <plan>...</plan> markdown block near the top of your response. Break the work into small subtasks so each one can be a commit.
- You are working inside a git worktree on a fresh feature branch. After each logical subtask, run \`git add -A && git commit -m "<concise subject>"\` — each commit is journaled as a subtask boundary.
- Run existing test/lint/typecheck commands if present and keep them green.
- Respect the repository's own CLAUDE.md / AGENTS.md and other AI convention files.
- When every acceptance criterion is met and tests pass, make a final commit and stop — the outer tool will push and open a PR.`;
}

function buildPrBody(story: Story): string {
  const ac = story.acceptanceCriteria.map((c) => `- [ ] ${c}`).join('\n');
  return `## Summary

${story.description}

## Acceptance criteria

${ac}

---

🤖 Auto-generated by NightCoder.`;
}

function extractPlanBlock(text: string): string | null {
  const m = PLAN_BLOCK_RE.exec(text);
  if (!m) return null;
  const trimmed = m[1].trim();
  return trimmed.length > 0 ? trimmed : null;
}

/**
 * Degraded-mode journal populator. When we can't install our post-commit hook
 * (a foreign hook is already there), poll `git log` on the worktree branch
 * every 2s and append new commits to the task journal.
 */
function startCommitPoller(args: {
  repoPath: string;
  worktreePath: string;
  branch: string;
  baseBranch: string;
  taskId: string;
  onInfo: (msg: string) => void;
}): () => Promise<void> {
  const seen = new Set<string>();
  let stopped = false;
  let inFlight: Promise<void> | null = null;

  const poll = async () => {
    if (stopped) return;
    try {
      const { stdout } = await execFileP(
        'git',
        ['log', '--format=%H%x1f%at%x1f%s', `${args.baseBranch}..HEAD`],
        { cwd: args.worktreePath },
      );
      const lines = stdout.split('\n').filter((l) => l.trim().length > 0).reverse();
      for (const line of lines) {
        const [hash, tsStr, ...subjectParts] = line.split('\x1f');
        if (!hash || seen.has(hash)) continue;
        seen.add(hash);
        const timestamp = Number.isFinite(Number(tsStr)) ? Number(tsStr) : Math.floor(Date.now() / 1000);
        const subject = subjectParts.join('\x1f');
        await appendJournalLine(args.repoPath, args.taskId, { timestamp, hash, subject });
      }
    } catch {
      // transient (base branch missing in worktree, race with git) — ignore and retry.
    }
  };

  const interval = setInterval(() => {
    if (inFlight) return;
    inFlight = poll().finally(() => { inFlight = null; });
  }, POLL_INTERVAL_MS);

  args.onInfo(`commit journal: polling ${args.baseBranch}..HEAD every ${POLL_INTERVAL_MS}ms (foreign post-commit hook detected)`);

  return async () => {
    stopped = true;
    clearInterval(interval);
    if (inFlight) {
      try { await inFlight; } catch { /* ignore */ }
    }
    await poll().catch(() => {});
  };
}

export async function executeStory(args: {
  story: Story;
  storyIndex: number;
  repoPath: string;
  baseBranch: string;
  usedSlugs: Set<string>;
  onEvent: (event: StoryExecutionEvent) => void;
  signal: { cancelled: boolean };
}): Promise<StoryExecutionResult> {
  const { story, repoPath, baseBranch, usedSlugs, onEvent, signal } = args;
  const slugBase = slugify(`${args.storyIndex + 1}-${story.title}`);

  const release = tryClaimStory(repoPath, slugBase);
  if (!release) {
    onEvent({
      kind: 'log',
      stream: 'info',
      line: `story "${story.title}" is already being executed — skipping duplicate start`,
    });
    return { success: false, error: 'already running', duplicate: true };
  }

  const slug = uniqueSlug(slugBase, usedSlugs);
  usedSlugs.add(slug);

  onEvent({ kind: 'status', status: 'running' });

  let worktree: WorktreeHandle | null = null;
  let stopPoller: (() => Promise<void>) | null = null;
  let reachedReview = false;
  try {
    await ensureTaskDir(repoPath, story).catch((e) => {
      onEvent({ kind: 'log', stream: 'stderr', line: `task dir prep failed: ${e instanceof Error ? e.message : String(e)}` });
    });

    worktree = await createWorktree({
      repoPath,
      slug,
      baseBranch,
      onInfo: (msg) => onEvent({ kind: 'log', stream: 'info', line: msg }),
    });
    onEvent({ kind: 'log', stream: 'info', line: `worktree ${worktree.path} (branch ${worktree.branch})` });

    const hookResult = await installPostCommitHook(repoPath).catch((e) => {
      onEvent({
        kind: 'log',
        stream: 'stderr',
        line: `post-commit hook install failed: ${e instanceof Error ? e.message : String(e)}`,
      });
      return null;
    });
    if (hookResult?.kind === 'foreign') {
      onEvent({
        kind: 'log',
        stream: 'info',
        line: `post-commit hook exists and is not ours — falling back to polling. First lines: ${hookResult.preview.split('\n').join(' | ')}`,
      });
      stopPoller = startCommitPoller({
        repoPath,
        worktreePath: worktree.path,
        branch: worktree.branch,
        baseBranch,
        taskId: story.taskId,
        onInfo: (msg) => onEvent({ kind: 'log', stream: 'info', line: msg }),
      });
    } else if (hookResult) {
      onEvent({ kind: 'log', stream: 'info', line: `post-commit hook ${hookResult.kind}` });
    }

    const abort = new AbortController();
    const cancelWatcher = setInterval(() => {
      if (signal.cancelled && !abort.signal.aborted) abort.abort();
    }, 250);

    const journalAbs = path.resolve(journalPath(repoPath, story.taskId));
    let assistantText = '';

    const handle = runClaudeInWorktree(
      {
        cwd: worktree.path,
        prompt: buildPrompt(story),
        addDirs: [],
        model: story.model,
        env: { NIGHTCODER_JOURNAL_PATH: journalAbs },
      },
      {
        onEvent: (e) => {
          const tag = e.kind === 'tool' ? `tool: ${e.line}` : e.kind === 'text' ? e.line : e.kind === 'error' ? `error: ${e.line}` : e.line;
          onEvent({ kind: 'log', stream: 'stdout', line: tag });
        },
        onStderr: (line) => onEvent({ kind: 'log', stream: 'stderr', line }),
        onAssistantText: (text) => { assistantText += text; },
      }
    );

    const runnerCancelWatcher = setInterval(() => {
      if (signal.cancelled) handle.cancel();
    }, 250);

    const result = await handle.result;
    clearInterval(runnerCancelWatcher);

    const planBlock = extractPlanBlock(assistantText);
    if (planBlock) {
      await writePlanMd(repoPath, story.taskId, planBlock).catch((e) => {
        onEvent({ kind: 'log', stream: 'stderr', line: `plan.md write failed: ${e instanceof Error ? e.message : String(e)}` });
      });
      onEvent({ kind: 'log', stream: 'info', line: 'captured plan block → plan.md' });
    }

    if (signal.cancelled) {
      clearInterval(cancelWatcher);
      onEvent({ kind: 'status', status: 'cancelled' });
      return { success: false, error: 'cancelled' };
    }
    if (!result.success) {
      clearInterval(cancelWatcher);
      onEvent({ kind: 'status', status: 'failed' });
      return { success: false, error: result.error ?? `stop_reason=${result.stopReason ?? '?'}` };
    }

    try {
      onEvent({ kind: 'status', status: 'pushing' });
      const madeCommit = await commitAllIfDirty(
        worktree.path,
        `chore(nightcoder): flush uncommitted changes for ${story.title}`,
        { signal: abort.signal }
      );
      if (madeCommit) onEvent({ kind: 'log', stream: 'info', line: 'flushed uncommitted changes into final commit' });
      await gitPush(worktree.path, worktree.branch, { signal: abort.signal });
      onEvent({ kind: 'log', stream: 'info', line: `pushed ${worktree.branch}` });
      const prUrl = await ghCreatePr({
        cwd: worktree.path,
        title: story.title,
        body: buildPrBody(story),
        baseBranch,
        signal: abort.signal,
      });
      onEvent({ kind: 'pr', url: prUrl, branch: worktree.branch });
      onEvent({ kind: 'status', status: 'review' });
      reachedReview = true;
      return { success: true, prUrl, branch: worktree.branch };
    } finally {
      clearInterval(cancelWatcher);
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    if (signal.cancelled) {
      onEvent({ kind: 'log', stream: 'info', line: 'cancelled during push/PR' });
      onEvent({ kind: 'status', status: 'cancelled' });
      return { success: false, error: 'cancelled' };
    }
    onEvent({ kind: 'log', stream: 'stderr', line: message });
    onEvent({ kind: 'status', status: 'failed' });
    return { success: false, error: message };
  } finally {
    if (stopPoller) {
      await stopPoller().catch(() => {});
    }
    // Keep the worktree around on failure / cancellation so the user can resume
    // into it; only clean up on the success path where the branch is already
    // safely pushed. `release()` always runs — the in-memory slug claim is
    // released even if the worktree persists.
    if (worktree && reachedReview) {
      await worktree.cleanup().catch((e) => {
        onEvent({ kind: 'log', stream: 'stderr', line: `worktree cleanup failed: ${e instanceof Error ? e.message : String(e)}` });
      });
    } else if (worktree) {
      onEvent({
        kind: 'log',
        stream: 'info',
        line: `worktree kept at ${worktree.path} (branch ${worktree.branch}) for potential resume`,
      });
    }
    release();
  }
}
