/* global React */
const { useState, useEffect, useRef, useMemo, useCallback } = React;

// ────────────────────────────────────────────────────────────
// Mock data  — realistic fixtures for the prototype
// ────────────────────────────────────────────────────────────

const nowMs = Date.now();
const mins = (n) => n * 60 * 1000;

const FOLDER = {
  path: '/Users/zibby/Workspace/Zibby-2.0',
  name: 'Zibby-2.0',
  isGitRepo: true,
  hasOrigin: true,
  branch: 'main',
  recent: [
    '/Users/zibby/Workspace/Zibby-2.0',
    '/Users/zibby/Workspace/graphify',
    '/Users/zibby/code/scratch-pad',
  ],
  tree: [
    { name: 'apps', type: 'dir', children: [
      { name: 'desktop', type: 'dir', children: [
        { name: 'src', type: 'dir', children: [
          { name: 'main', type: 'dir', children: [
            { name: 'index.ts', type: 'file' },
            { name: 'state-store.ts', type: 'file' },
            { name: 'runner.ts', type: 'file' },
            { name: 'ipc.ts', type: 'file' },
          ]},
          { name: 'renderer', type: 'dir', children: [
            { name: 'components', type: 'dir', children: [
              { name: 'LogPanel.tsx', type: 'file' },
              { name: 'StoryCard.tsx', type: 'file' },
              { name: 'UsageBar.tsx', type: 'file' },
              { name: 'CommandPalette.tsx', type: 'file' },
              { name: 'TaskDrawer.tsx', type: 'file' },
            ]},
            { name: 'App.tsx', type: 'file' },
            { name: 'main.tsx', type: 'file' },
            { name: 'styles.css', type: 'file' },
          ]},
          { name: 'preload', type: 'dir', children: [
            { name: 'index.ts', type: 'file' },
          ]},
        ]},
        { name: 'package.json', type: 'file' },
        { name: 'tsconfig.json', type: 'file' },
        { name: 'vite.config.ts', type: 'file' },
      ]},
    ]},
    { name: 'libs', type: 'dir', children: [
      { name: 'shared', type: 'dir', children: [
        { name: 'types.ts', type: 'file' },
        { name: 'schema.ts', type: 'file' },
      ]},
      { name: 'agents', type: 'dir', children: [
        { name: 'plan.ts', type: 'file' },
        { name: 'code.ts', type: 'file' },
        { name: 'qa.ts', type: 'file' },
      ]},
    ]},
    { name: 'docs', type: 'dir', children: [
      { name: 'architecture.md', type: 'file' },
      { name: 'agents.md', type: 'file' },
      { name: 'tasks-spec.md', type: 'file' },
    ]},
    { name: '.agents', type: 'dir', children: [
      { name: 'claude.json', type: 'file' },
      { name: 'system.md', type: 'file' },
    ]},
    { name: 'package.json', type: 'file' },
    { name: 'pnpm-workspace.yaml', type: 'file' },
    { name: 'README.md', type: 'file' },
    { name: '.env', type: 'file' },
    { name: '.gitignore', type: 'file' },
  ],
};

const MODELS = ['sonnet', 'opus', 'haiku'];

const SEED_TASKS = [
  {
    id: 't1',
    index: 0,
    title: 'Kanban columns for task lifecycle',
    description:
      'Replace the single list with Queued / Running / Done columns. Cards drag between columns and persist order.',
    acceptance: [
      'Three columns render with correct counts',
      'Drag updates state + localStorage',
      'Keyboard reorder works (⌘↑/↓)',
    ],
    status: 'running',
    model: 'sonnet',
    branch: 'zibby/1-kanban-columns',
    prUrl: null,
    startedAt: nowMs - mins(6),
    endedAt: null,
    tokens: { in: 14820, out: 3940 },
    waitsOn: [],
    affectedFiles: ['App.tsx', 'components/Column.tsx', 'state-store.ts'],
    logs: runningLogs(),
    diff: sampleDiff(),
  },
  {
    id: 't2',
    index: 1,
    title: 'Task detail drawer with tabs',
    description: 'Click a task → drawer opens with Logs, Diff, Details tabs. Keyboard: j/k to navigate.',
    acceptance: ['Drawer overlays main view', 'Tabs remember last selection', 'Esc closes drawer'],
    status: 'queued',
    model: 'sonnet',
    branch: null,
    prUrl: null,
    startedAt: null,
    endedAt: null,
    tokens: null,
    waitsOn: [0],
    affectedFiles: ['components/TaskDrawer.tsx'],
    logs: [],
    diff: null,
  },
  {
    id: 't3',
    index: 2,
    title: 'Command palette (⌘K)',
    description:
      'Fuzzy palette to jump to tasks, run actions, switch folder. Uses fuse-like scoring on title/description.',
    acceptance: [
      '⌘K opens, Esc closes',
      'Keyboard nav with ↑/↓',
      'Commands: run all, add task, change folder, toggle theme',
    ],
    status: 'pending',
    model: 'opus',
    branch: null,
    prUrl: null,
    startedAt: null,
    endedAt: null,
    tokens: null,
    waitsOn: [],
    affectedFiles: [],
    logs: [],
    diff: null,
  },
  {
    id: 't4',
    index: 3,
    title: 'Usage ring with reset countdown',
    description: 'Show 5h and weekly usage as rings with a live countdown until reset.',
    acceptance: ['Rings update live via onUsageUpdate', 'Countdown ticks each second'],
    status: 'review',
    model: 'sonnet',
    branch: 'zibby/4-usage-ring',
    prUrl: 'https://github.com/zibby/zibby-2.0/pull/42',
    startedAt: nowMs - mins(48),
    endedAt: nowMs - mins(32),
    tokens: { in: 9180, out: 2640 },
    waitsOn: [],
    affectedFiles: ['components/UsageBar.tsx', 'components/UsageRing.tsx'],
    logs: doneLogs(),
    diff: sampleDiffSmall(),
  },
  {
    id: 't5',
    index: 4,
    title: 'Diff preview inline in drawer',
    description: 'Parse git diff and colorize inline. Show per-file collapse.',
    acceptance: ['Added/removed gutters render', 'Files collapse independently', 'Monospace fits 100ch'],
    status: 'done',
    model: 'sonnet',
    branch: 'zibby/5-diff-preview',
    prUrl: 'https://github.com/zibby/zibby-2.0/pull/41',
    startedAt: nowMs - mins(140),
    endedAt: nowMs - mins(110),
    tokens: { in: 21440, out: 6120 },
    waitsOn: [],
    affectedFiles: ['components/Diff.tsx'],
    logs: doneLogs(),
    diff: sampleDiff(),
  },
  {
    id: 't6',
    index: 5,
    title: 'Failed push retries with backoff',
    description: 'If `git push` fails, retry 3× with exponential backoff, then surface the error.',
    acceptance: ['Retries visible in logs', 'Final error is structured'],
    status: 'failed',
    model: 'sonnet',
    branch: 'zibby/6-push-retry',
    prUrl: null,
    startedAt: nowMs - mins(22),
    endedAt: nowMs - mins(18),
    tokens: { in: 4200, out: 890 },
    waitsOn: [],
    affectedFiles: ['main/runner.ts'],
    logs: failedLogs(),
    diff: null,
  },
  {
    id: 't7',
    index: 6,
    title: 'Notifications on run complete',
    description: 'Show a native desktop notification when a task finishes (done or failed).',
    acceptance: ['Respects OS permission', 'Click focuses the task'],
    status: 'pending',
    model: 'haiku',
    branch: null,
    prUrl: null,
    startedAt: null,
    endedAt: null,
    tokens: null,
    waitsOn: [2],
    affectedFiles: [],
    logs: [],
    diff: null,
  },
  {
    id: 'a1',
    index: 100,
    title: 'Initial worktree bootstrapping',
    description: 'Create the .worktrees directory layout and helper script.',
    acceptance: ['Worktree per task', 'Cleanup on archive'],
    status: 'done',
    model: 'sonnet',
    branch: 'zibby/0-bootstrap',
    prUrl: 'https://github.com/zibby/zibby-2.0/pull/12',
    startedAt: nowMs - mins(60 * 24 * 3),
    endedAt: nowMs - mins(60 * 24 * 3 - 22),
    tokens: { in: 5400, out: 1100 },
    waitsOn: [], affectedFiles: ['main/worktree.ts'],
    archived: true, archivedAt: nowMs - mins(60 * 24 * 2),
    logs: [], diff: null,
  },
  {
    id: 'a2',
    index: 101,
    title: 'Migrate Electron 27 → 30',
    description: 'Bump Electron, fix sandbox + contextBridge regressions.',
    acceptance: ['App launches', 'IPC unchanged'],
    status: 'done',
    model: 'opus',
    branch: 'zibby/electron-30',
    prUrl: 'https://github.com/zibby/zibby-2.0/pull/19',
    startedAt: nowMs - mins(60 * 24 * 5),
    endedAt: nowMs - mins(60 * 24 * 5 - 47),
    tokens: { in: 12300, out: 3200 },
    waitsOn: [], affectedFiles: ['package.json','main/index.ts'],
    archived: true, archivedAt: nowMs - mins(60 * 24 * 4),
    logs: [], diff: null,
  },
  {
    id: 'a3',
    index: 102,
    title: 'Token budget warnings',
    description: 'Soft cap + hard cap on per-task token usage with banner.',
    acceptance: ['Warn at 80%', 'Halt at 100%'],
    status: 'failed',
    model: 'sonnet',
    branch: 'zibby/token-budget',
    prUrl: null,
    startedAt: nowMs - mins(60 * 24 * 8),
    endedAt: nowMs - mins(60 * 24 * 8 - 12),
    tokens: { in: 2100, out: 410 },
    waitsOn: [], affectedFiles: [],
    archived: true, archivedAt: nowMs - mins(60 * 24 * 7),
    logs: [], diff: null,
  },
  {
    id: 'a4',
    index: 103,
    title: 'Settings schema v2',
    description: 'Move .claude/settings.local.json under a versioned schema.',
    acceptance: ['Migration script', 'Backwards compat'],
    status: 'done',
    model: 'sonnet',
    branch: 'zibby/settings-v2',
    prUrl: 'https://github.com/zibby/zibby-2.0/pull/27',
    startedAt: nowMs - mins(60 * 24 * 12),
    endedAt: nowMs - mins(60 * 24 * 12 - 35),
    tokens: { in: 8200, out: 2100 },
    waitsOn: [], affectedFiles: ['main/settings.ts'],
    archived: true, archivedAt: nowMs - mins(60 * 24 * 10),
    logs: [], diff: null,
  },
  {
    id: 'a5',
    index: 104,
    title: 'Crash reporter pipeline',
    description: 'Pipe renderer crashes into local file + optional sentry.',
    acceptance: ['Stack traces', 'Opt-in toggle'],
    status: 'cancelled',
    model: 'haiku',
    branch: 'zibby/crash-reporter',
    prUrl: null,
    startedAt: nowMs - mins(60 * 24 * 15),
    endedAt: nowMs - mins(60 * 24 * 15 - 4),
    tokens: { in: 800, out: 80 },
    waitsOn: [], affectedFiles: [],
    archived: true, archivedAt: nowMs - mins(60 * 24 * 14),
    logs: [], diff: null,
  },
];

function runningLogs() {
  return [
    { s: 'info', l: '✓ mirrored local AI settings: .claude/settings.local.json' },
    { s: 'info', l: '✓ worktree /Users/zibby/Workspace/Zibby-2.0/.worktrees/1-kanban-columns (branch zibby/1-kanban-columns)' },
    { s: 'info', l: '✓ session started (model=claude-sonnet-4-6)' },
    { s: 'out', l: '→ reading apps/desktop/src/renderer/App.tsx' },
    { s: 'out', l: '→ reading apps/desktop/src/renderer/components/StoryCard.tsx' },
    { s: 'out', l: 'Plan: extract Column component, introduce drag handlers via pointer events.' },
    { s: 'out', l: '→ creating components/Column.tsx' },
    { s: 'out', l: '→ creating components/kanban-dnd.ts' },
    { s: 'out', l: '→ editing App.tsx  (+142 −31)' },
    { s: 'out', l: '→ editing state-store.ts  (+18 −2)' },
    { s: 'out', l: 'running: pnpm -w typecheck' },
    { s: 'out', l: 'tsc --noEmit (renderer) …' },
    { s: 'err', l: 'apps/desktop/src/renderer/components/Column.tsx(42,9): TS2322: Type \'string\' is not assignable to type \'StoryStatus\'.' },
    { s: 'out', l: 'fixing type narrowing on onDrop handler' },
    { s: 'out', l: '→ editing components/Column.tsx  (+8 −4)' },
    { s: 'out', l: 'running: pnpm -w typecheck' },
    { s: 'info', l: 'typecheck ✓' },
    { s: 'out', l: 'running: pnpm -w test --filter desktop' },
  ];
}
function doneLogs() {
  return [
    { s: 'info', l: '✓ session started' },
    { s: 'out', l: '→ reading files …' },
    { s: 'out', l: '→ implementing feature' },
    { s: 'info', l: 'typecheck ✓' },
    { s: 'info', l: 'tests ✓  12 passed' },
    { s: 'out', l: 'git add -A && git commit -m "feat: usage ring with reset countdown"' },
    { s: 'out', l: 'git push -u origin zibby/4-usage-ring' },
    { s: 'info', l: '✓ PR opened: https://github.com/zibby/zibby-2.0/pull/42' },
  ];
}
function failedLogs() {
  return [
    { s: 'info', l: '✓ session started' },
    { s: 'out', l: '→ implementing retry with backoff' },
    { s: 'out', l: 'git push -u origin zibby/6-push-retry' },
    { s: 'err', l: 'remote: Permission to zibby/zibby-2.0.git denied to bot.' },
    { s: 'err', l: 'fatal: unable to access …: The requested URL returned 403' },
    { s: 'out', l: 'retry 1/3 in 2s …' },
    { s: 'err', l: 'remote: Permission denied (again)' },
    { s: 'out', l: 'retry 2/3 in 4s …' },
    { s: 'err', l: 'remote: Permission denied' },
    { s: 'err', l: '✗ push failed after 3 attempts' },
  ];
}

function sampleDiff() {
  return [
    {
      file: 'apps/desktop/src/renderer/App.tsx',
      add: 142, del: 31,
      lines: [
        { t: 'hunk', l: '@@ -188,7 +188,12 @@ export default function App() {' },
        { t: 'ctx',  l: '  const [plan, setPlan] = useState<RefinedPlan | null>(null);' },
        { t: 'del',  l: "  const [selectedIndex, setSelectedIndex] = useState<number>(0);" },
        { t: 'add',  l: "  const [selectedId, setSelectedId] = useState<string | null>(null);" },
        { t: 'add',  l: "  const [drawerTab, setDrawerTab] = useState<'logs' | 'diff' | 'details'>('logs');" },
        { t: 'ctx',  l: '  const [error, setError] = useState<string | null>(null);' },
        { t: 'hunk', l: '@@ -241,6 +246,11 @@' },
        { t: 'add',  l: '  const moveTask = (id: string, to: StoryStatus) => {' },
        { t: 'add',  l: '    setRuntime((r) => ({ ...r, [id]: { ...r[id], status: to } }));' },
        { t: 'add',  l: '  };' },
      ],
    },
    {
      file: 'apps/desktop/src/renderer/components/Column.tsx',
      add: 96, del: 0,
      lines: [
        { t: 'hunk', l: '@@ -0,0 +1,96 @@' },
        { t: 'add',  l: "import { useState } from 'react';" },
        { t: 'add',  l: "import type { Story, StoryStatus } from '@zibby/shared-types/ipc';" },
        { t: 'add',  l: '' },
        { t: 'add',  l: 'export function Column({ title, status, stories, onDrop }: Props) {' },
        { t: 'add',  l: '  const [hover, setHover] = useState(false);' },
        { t: 'add',  l: '  return (' },
        { t: 'add',  l: '    <div className={`column ${hover ? \'col-drop-hint\' : \'\'}`} />' },
        { t: 'add',  l: '  );' },
        { t: 'add',  l: '}' },
      ],
    },
  ];
}
function sampleDiffSmall() {
  return [
    {
      file: 'apps/desktop/src/renderer/components/UsageRing.tsx',
      add: 68, del: 0,
      lines: [
        { t: 'hunk', l: '@@ -0,0 +1,68 @@' },
        { t: 'add',  l: 'export function UsageRing({ pct, size=36 }: { pct: number; size?: number }) {' },
        { t: 'add',  l: '  const r = (size - 4) / 2;' },
        { t: 'add',  l: '  const circ = 2 * Math.PI * r;' },
        { t: 'add',  l: '  …' },
        { t: 'add',  l: '}' },
      ],
    },
  ];
}

// Usage stub
const USAGE = {
  fiveHour: { usedPct: 39, resetsInMs: mins(143), burnRate: 4200 },
  weekly:   { usedPct: 37, resetsInMs: mins(60 * 24 * 3 + 60 * 7), burnRate: 260000 },
};

window.ZIBBY = { FOLDER, MODELS, SEED_TASKS, USAGE };
